/** Wraps the PetNES WASM module with the same API as FableNES's Nes class. */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — generated by Emscripten, no types available
import PetNesModuleFactory from "../wasm-out/petnes-core.js";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type WasmModule = any;

let _mod: WasmModule | null = null;

export async function initWasm(): Promise<void> {
  _mod = await PetNesModuleFactory({
    locateFile: (file: string) => `/wasm/${file}`,
  });
}

function mod(): WasmModule {
  if (!_mod) throw new Error("WASM not initialised; call initWasm() first");
  return _mod;
}

// ---------------------------------------------------------------------------
// Controller proxy
// ---------------------------------------------------------------------------
export class Controller {
  private mask = 0;
  constructor(
    private readonly getHandle: () => number,
    private readonly index: number,
  ) {}

  setButton(button: number, pressed: boolean): void {
    if (pressed) this.mask |= 1 << button;
    else         this.mask &= ~(1 << button);
    mod()._nes_controller_set(this.getHandle(), this.index, this.mask);
  }

  getState() { return {}; }
  setState(_s: unknown) {}
}

// ---------------------------------------------------------------------------
// APU proxy
// ---------------------------------------------------------------------------
export class ApuProxy {
  private scratchPtr = 0;
  private scratchLen = 0;

  constructor(private readonly getHandle: () => number) {}

  setSampleRate(sr: number): void {
    mod()._nes_set_sample_rate(this.getHandle(), sr);
  }

  available(): number {
    // Always return positive; drainSamples will return 0 if the ring is empty
    return 4096;
  }

  setChannelMute(ch: number, muted: boolean): void {
    mod()._nes_set_channel_mute(this.getHandle(), ch, muted ? 1 : 0);
  }

  drainSamples(out: Float32Array): number {
    const m = mod();
    // Grow scratch buffer if needed
    if (this.scratchLen < out.length) {
      if (this.scratchPtr) m._free(this.scratchPtr);
      this.scratchPtr = m._malloc(out.length * 4);
      this.scratchLen = out.length;
    }
    const n = m._nes_apu_drain(this.getHandle(), this.scratchPtr, out.length);
    if (n > 0) {
      // Use a fresh HEAPF32 view in case the heap grew since module init
      out.set(new Float32Array(m.HEAPF32.buffer, this.scratchPtr, n));
    }
    return n;
  }
}

// ---------------------------------------------------------------------------
// Cart proxy (only mapperId is needed by main.ts status display)
// ---------------------------------------------------------------------------
export class CartProxy {
  mapperId = 0;
}

export function setPaletteEntry(idx: number, r: number, g: number, b: number): void {
  mod()._nes_set_palette_entry(idx, r, g, b);
}


// ---------------------------------------------------------------------------
// Nes — drop-in replacement for FableNES's Nes class
// ---------------------------------------------------------------------------
export class Nes {
  private handle: number;
  private fbByteOffset: number;

  readonly controller1: Controller;
  readonly controller2: Controller;
  readonly apu: ApuProxy;
  readonly cart: CartProxy = new CartProxy();

  constructor(romData: Uint8Array, _audioSampleRate = 44100) {
    const m = mod();
    const romPtr = m._malloc(romData.length);
    m.HEAPU8.set(romData, romPtr);
    this.handle = m._nes_create(romPtr, romData.length);
    m._free(romPtr);
    if (!this.handle) throw new Error("Failed to create NES (bad ROM or unsupported mapper)");

    this.fbByteOffset = m._nes_get_framebuffer(this.handle);

    const getHandle = () => this.handle;
    this.controller1 = new Controller(getHandle, 0);
    this.controller2 = new Controller(getHandle, 1);
    this.apu         = new ApuProxy(getHandle);
  }

  get framebuffer(): Uint32Array {
    return new Uint32Array(mod().HEAPU8.buffer, this.fbByteOffset, 256 * 240);
  }

  stepFrame(): void { mod()._nes_step_frame(this.handle); }
  reset():     void { mod()._nes_reset(this.handle); }

  serialize(): string {
    const m   = mod();
    const ptr = m._nes_serialize(this.handle);
    const str = m.UTF8ToString(ptr);
    m._nes_free_string(ptr);
    return str;
  }

  deserialize(json: string): void {
    const m   = mod();
    const len = m.lengthBytesUTF8(json) + 1;
    const ptr = m._malloc(len);
    m.stringToUTF8(json, ptr, len);
    m._nes_deserialize(this.handle, ptr);
    m._free(ptr);
  }


  destroy(): void {
    if (this.handle) { mod()._nes_destroy(this.handle); this.handle = 0; }
  }
}
